### ISSUE TITLE
模板列表多列有bug 

### ISSUE THREAD

**Issue by CHENJKNB** [mini-software/MiniWord#47]
模板
![image](https://user-images.githubusercontent.com/18523983/195056564-8a3df0d9-331a-4018-aced-c634527a850f.png)

输出数据![image](https://user-images.githubusercontent.com/18523983/195056362-8637ac6b-39a6-4b61-91f8-bddeec02c2fc.png)

**Comment by intel0620** [comment]
我也是遇到這個問題,表格最後如有多一列就會產生這種問題.

**Comment by itldg** [comment]
似乎表格是始终插入到最后,我测试了 #18 的代码,仅修改了模板,将两个表格合并

**原本的效果**

![image](https://github.com/mini-software/MiniWord/assets/13432299/3efc183b-922d-4168-8d8a-882348199af0)

![image](https://github.com/mini-software/MiniWord/assets/13432299/5ebfc1d3-d332-45a5-9171-ba9c07b3b331)

**合并后的效果**

![image](https://github.com/mini-software/MiniWord/assets/13432299/f1879990-38ba-4941-bf0f-9cfc7435f973)

![image](https://github.com/mini-software/MiniWord/assets/13432299/5340a1a5-21b6-41f0-80b8-adca40bca75a)

**Comment by itldg** [comment]
尝试修复后的效果
![image](https://github.com/mini-software/MiniWord/assets/13432299/7b54e857-5026-4d00-8a3f-16155a917eec)
