### ISSUE TITLE
main 分支中 缺少 SaveAsByTemplateImplAsync 方法

### ISSUE THREAD

**Issue by gaoshang212** [mini-software/MiniWord#91]
![image](https://github.com/user-attachments/assets/570250f6-38f3-4c16-9b24-3248ddba2498)

项目中没有搜索到 对应的实现

**Comment by masterworgen** [comment]
Just remove from code

**Comment by masterworgen** [comment]
I fixed it in this PR https://github.com/mini-software/MiniWord/pull/93

**Comment by masterworgen** [comment]
This PR was merged, i close this issue
